### ISSUE TITLE
Initial path does not trigger a route

### ISSUE THREAD

**Issue by ianhd** [haithembelhaj/slim-router#11]
I've defined a few routes, and if I open up my browser and go to one of them directly, the route handler will not fire off. The route handlers only fire off if I do `router.navigate(...)`. **Is there a way to fire off the initial page load?**

Here's my code:

    var router = new Router();
    router.route('/test', function() { console.log("test"); });

Now, if I go directly to `example.com/test`, I don't see the `console.log` trigger. However, if I go directly to `example.com/another-route`, then do `router.navigate('/test')`, the `console.log("test");` will trigger. Thanks!

**Comment by fynjah** [comment]
Thanks about `router.start()`. In my case, there was missing slash. so i did a pull request with `append_slash` option

**Comment by haithembelhaj** [comment]
`router.start()` is the way to go.
